#!/bin/bash
# echo Removing fonts
# find . -type f -name "*.ttf" -exec rm -f {} \;
#
# echo Removing PowerShell
# rm -rf 'Files/Program Files/WindowsPowerShell'
# rm -rf 'Files/Windows/System32/WindowsPowerShell'
#
# echo Removing WinSxS
# rm -rf 'Files/Windows/WinSxS'
#
# echo Removing DotNetCore
# rm -rf 'Files/Windows/System32/DotNetCore'
#
# echo Remove Branding
# rm -rf 'Files/Windows/Branding'
#
# echo Remove DriverStore
# rm -rf 'Files/Windows/System32/DriverStore'
#
# echo Remove other System32 DLLs
# mkdir /tmp/sav/
# cp Files/Windows/System32/ActionQueue.dll /tmp/sav/
# cp Files/Windows/System32/AppXDeploymentServer.dll /tmp/sav/
# cp Files/Windows/System32/BrokerLib.dll /tmp/sav/
# cp Files/Windows/System32/CExecSvc.exe /tmp/sav/
# cp Files/Windows/System32/CSystemEventsBrokerClient.dll /tmp/sav/
# cp Files/Windows/System32/EventAggregation.dll /tmp/sav/
# cp Files/Windows/System32/FirewallAPI.dll /tmp/sav/
# cp Files/Windows/System32/FlightSettings.dll /tmp/sav/
# cp Files/Windows/System32/IPHLPAPI.DLL /tmp/sav/
# cp Files/Windows/System32/KBDUS.DLL /tmp/sav/
# cp Files/Windows/System32/KerbClientShared.dll /tmp/sav/
# cp Files/Windows/System32/KernelBase.dll /tmp/sav/
# cp Files/Windows/System32/NtlmShared.dll /tmp/sav/
# cp Files/Windows/System32/RpcEpMap.dll /tmp/sav/
# cp Files/Windows/System32/RpcRtRemote.dll /tmp/sav/
# cp Files/Windows/System32/SHCore.dll /tmp/sav/
# cp Files/Windows/System32/StateRepository.Core.dll /tmp/sav/
# cp Files/Windows/System32/SystemEventsBrokerServer.dll /tmp/sav/
# cp Files/Windows/System32/TSpkg.dll /tmp/sav/
# cp Files/Windows/System32/TimeBrokerClient.dll /tmp/sav/
# cp Files/Windows/System32/TimeBrokerServer.dll /tmp/sav/
# cp Files/Windows/System32/UserMgrProxy.dll /tmp/sav/
# cp Files/Windows/System32/WinTypes.dll /tmp/sav/
# cp Files/Windows/System32/Windows.StateRepository.dll /tmp/sav/
# cp Files/Windows/System32/Wldap32.dll /tmp/sav/
# cp Files/Windows/System32/WsmSvc.dll /tmp/sav/
# cp Files/Windows/System32/advapi32legacy.dll /tmp/sav/
# cp Files/Windows/System32/advapi32res.dll /tmp/sav/
# cp Files/Windows/System32/authz.dll /tmp/sav/
# cp Files/Windows/System32/basesrv.dll /tmp/sav/
# cp Files/Windows/System32/bcd.dll /tmp/sav/
# cp Files/Windows/System32/bcrypt.dll /tmp/sav/
# cp Files/Windows/System32/bcryptprimitives.dll /tmp/sav/
# cp Files/Windows/System32/cfgmgr32.dll /tmp/sav/
# cp Files/Windows/System32/cmd.exe /tmp/sav/
# cp Files/Windows/System32/combase.dll /tmp/sav/
# cp Files/Windows/System32/conkbd.dll /tmp/sav/
# cp Files/Windows/System32/credssp.dll /tmp/sav/
# cp Files/Windows/System32/crypt32.dll /tmp/sav/
# cp Files/Windows/System32/cryptbase.dll /tmp/sav/
# cp Files/Windows/System32/cryptcatsvc.dll /tmp/sav/
# cp Files/Windows/System32/cryptdll.dll /tmp/sav/
# cp Files/Windows/System32/cryptsp.dll /tmp/sav/
# cp Files/Windows/System32/cryptsvc.dll /tmp/sav/
# cp Files/Windows/System32/csrsrv.dll /tmp/sav/
# cp Files/Windows/System32/csrss.exe /tmp/sav/
# cp Files/Windows/System32/dab.dll /tmp/sav/
# cp Files/Windows/System32/dabapi.dll /tmp/sav/
# cp Files/Windows/System32/dbgcore.dll /tmp/sav/
# cp Files/Windows/System32/dbghelp.dll /tmp/sav/
# cp Files/Windows/System32/dhcpcore.dll /tmp/sav/
# cp Files/Windows/System32/dhcpcore6.dll /tmp/sav/
# cp Files/Windows/System32/dhcpcsvc.dll /tmp/sav/
# cp Files/Windows/System32/dhcpcsvc6.dll /tmp/sav/
# cp Files/Windows/System32/diagtrack.dll /tmp/sav/
# cp Files/Windows/System32/dnsapi.dll /tmp/sav/
# cp Files/Windows/System32/dnsrslvr.dll /tmp/sav/
# cp Files/Windows/System32/dpapisrv.dll /tmp/sav/
# cp Files/Windows/System32/dsparse.dll /tmp/sav/
# cp Files/Windows/System32/dsrole.dll /tmp/sav/
# cp Files/Windows/System32/fltLib.dll /tmp/sav/
# cp Files/Windows/System32/fwbase.dll /tmp/sav/
# cp Files/Windows/System32/gmsaclient.dll /tmp/sav/
# cp Files/Windows/System32/httpapi.dll /tmp/sav/
# cp Files/Windows/System32/ipconfig.exe /tmp/sav/
# cp Files/Windows/System32/joinutil.dll /tmp/sav/
# cp Files/Windows/System32/kerberos.dll /tmp/sav/
# cp Files/Windows/System32/kernel.appcore.dll /tmp/sav/
# cp Files/Windows/System32/kernel32legacy.dll /tmp/sav/
# cp Files/Windows/System32/logoncli.dll /tmp/sav/
# cp Files/Windows/System32/lsasrv.dll /tmp/sav/
# cp Files/Windows/System32/lsass.exe /tmp/sav/
# cp Files/Windows/System32/mi.dll /tmp/sav/
# cp Files/Windows/System32/mintdh.dll /tmp/sav/
# cp Files/Windows/System32/miutils.dll /tmp/sav/
# cp Files/Windows/System32/mpr.dll /tmp/sav/
# cp Files/Windows/System32/msasn1.dll /tmp/sav/
# cp Files/Windows/System32/msprivs.dll /tmp/sav/
# cp Files/Windows/System32/msv1_0.dll /tmp/sav/
# cp Files/Windows/System32/msvcp_win.dll /tmp/sav/
# cp Files/Windows/System32/msvcrt.dll /tmp/sav/
# cp Files/Windows/System32/mswsock.dll /tmp/sav/
# cp Files/Windows/System32/ncrypt.dll /tmp/sav/
# cp Files/Windows/System32/ncsi.dll /tmp/sav/
# cp Files/Windows/System32/netapi32.dll /tmp/sav/
# cp Files/Windows/System32/netlogon.dll /tmp/sav/
# cp Files/Windows/System32/netprovfw.dll /tmp/sav/
# cp Files/Windows/System32/netutils.dll /tmp/sav/
# cp Files/Windows/System32/nlasvc.dll /tmp/sav/
# cp Files/Windows/System32/nsi.dll /tmp/sav/
# cp Files/Windows/System32/nsisvc.dll /tmp/sav/
# cp Files/Windows/System32/ntasn1.dll /tmp/sav/
# cp Files/Windows/System32/ntdll.dll /tmp/sav/
# cp Files/Windows/System32/ntmarta.dll /tmp/sav/
# cp Files/Windows/System32/oleaut32.dll /tmp/sav/
# cp Files/Windows/System32/pcwum.dll /tmp/sav/
# cp Files/Windows/System32/powrprof.dll /tmp/sav/
# cp Files/Windows/System32/procthreadexthost.dll /tmp/sav/
# cp Files/Windows/System32/profapi.dll /tmp/sav/
# cp Files/Windows/System32/profsvc.dll /tmp/sav/
# cp Files/Windows/System32/rpcrt4.dll /tmp/sav/
# cp Files/Windows/System32/rpcss.dll /tmp/sav/
# cp Files/Windows/System32/rsaenh.dll /tmp/sav/
# cp Files/Windows/System32/samcli.dll /tmp/sav/
# cp Files/Windows/System32/samlib.dll /tmp/sav/
# cp Files/Windows/System32/samsrv.dll /tmp/sav/
# cp Files/Windows/System32/scecli.dll /tmp/sav/
# cp Files/Windows/System32/scesrv.dll /tmp/sav/
# cp Files/Windows/System32/schannel.dll /tmp/sav/
# cp Files/Windows/System32/schedsvc.dll /tmp/sav/
# cp Files/Windows/System32/sechost.dll /tmp/sav/
# cp Files/Windows/System32/secur32.dll /tmp/sav/
# cp Files/Windows/System32/services.exe /tmp/sav/
# cp Files/Windows/System32/smss.exe /tmp/sav/
# cp Files/Windows/System32/srvsvc.dll /tmp/sav/
# cp Files/Windows/System32/sscore.dll /tmp/sav/
# cp Files/Windows/System32/sspicli.dll /tmp/sav/
# cp Files/Windows/System32/sspisrv.dll /tmp/sav/
# cp Files/Windows/System32/svchost.exe /tmp/sav/
# cp Files/Windows/System32/sysntfy.dll /tmp/sav/
# cp Files/Windows/System32/taskschd.dll /tmp/sav/
# cp Files/Windows/System32/ubpm.dll /tmp/sav/
# cp Files/Windows/System32/ucrtbase.dll /tmp/sav/
# cp Files/Windows/System32/umpnpmgr.dll /tmp/sav/
# cp Files/Windows/System32/unattend.dll /tmp/sav/
# cp Files/Windows/System32/userenv.dll /tmp/sav/
# cp Files/Windows/System32/usermgr.dll /tmp/sav/
# cp Files/Windows/System32/usermgrcli.dll /tmp/sav/
# cp Files/Windows/System32/wbemcomn.dll /tmp/sav/
# cp Files/Windows/System32/wdigest.dll /tmp/sav/
# cp Files/Windows/System32/wdscore.dll /tmp/sav/
# cp Files/Windows/System32/wer.dll /tmp/sav/
# cp Files/Windows/System32/wevtapi.dll /tmp/sav/
# cp Files/Windows/System32/wevtsvc.dll /tmp/sav/
# cp Files/Windows/System32/windowsperformancerecordercontrol.dll /tmp/sav/
# cp Files/Windows/System32/winhttp.dll /tmp/sav/
# cp Files/Windows/System32/wininit.exe /tmp/sav/
# cp Files/Windows/System32/winnsi.dll /tmp/sav/
# cp Files/Windows/System32/winsrv.dll /tmp/sav/
# cp Files/Windows/System32/wintrust.dll /tmp/sav/
# cp Files/Windows/System32/wkscli.dll /tmp/sav/
# cp Files/Windows/System32/wkssvc.dll /tmp/sav/
# cp Files/Windows/System32/wldp.dll /tmp/sav/
# cp Files/Windows/System32/wmiclnt.dll /tmp/sav/
# cp Files/Windows/System32/ws2_32.dll /tmp/sav/
# cp Files/Windows/System32/xmllite.dll /tmp/sav/
# rm -f Files/Windows/System32/*.exe
# rm -f Files/Windows/System32/A*.dll
# rm -f Files/Windows/System32/Cert*.dll
# rm -f Files/Windows/System32/Dbg*.dll
# rm -f Files/Windows/System32/dbg*.dll
# rm -f Files/Windows/System32/esent*.dll
# rm -f Files/Windows/System32/iertutil*.dll
# rm -f Files/Windows/System32/mispace*.dll
# rm -f Files/Windows/System32/Mrm*.dll
# rm -f Files/Windows/System32/MPSSVC.dll
# rm -f Files/Windows/System32/msdelta.dll
# rm -f Files/Windows/System32/msxml*.dll
# rm -f Files/Windows/System32/msvc*.dll
# rm -f Files/Windows/System32/O*.dll
# rm -f Files/Windows/System32/o*.dll
# rm -f Files/Windows/System32/P*.dll
# rm -f Files/Windows/System32/p*.dll
# rm -f Files/Windows/System32/storage*.dll
# rm -f Files/Windows/System32/twin*.dll
# rm -f Files/Windows/System32/url*.dll
# rm -f Files/Windows/System32/v*.dll
# rm -f Files/Windows/System32/webservice*.dll
# rm -f Files/Windows/System32/Windows.*.dll
# rm -f Files/Windows/System32/windows*.dll
# rm -f Files/Windows/System32/wuaueng.dll
# mv /tmp/sav/* Files/Windows/System32/

#echo Installing http.exe
#cp /work/http.exe Files/Windows/System32/http.exe

echo Creating Tar
tar czf $1 Files
